development:
  adapter: postgresql
  encoding: unicode
  database: AeroSanidad_development
  pool: 5
  username: postgres 
  password: postgres
  host: localhost



test:
  adapter: postgresql
  encoding: unicode
  database: AeroSanidad_test
  pool: 5
  username: postgres 
  password: postgres
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: Sinstock_production
  pool: 5
  username: postgres
  password: postgres
  host: localhost
